### PR TITLE
Update library to work on latest CsvHelper

### PR DESCRIPTION
**Pull request by kfrancis**

### CODE REVIEW

**Comment by kfrancis** [comment]
My primary reason for this was to get this to work in NetStandard, but then also get this updated with the latest CsvHelper breaking changes.

**Review by rtrice1 — APPROVED** [review]

**Comment by VerdonTrigance** [comment]
Is it working PR? Why it is still not merged?

**Comment by christophano** [comment]
Hi, I'm not actively developing this project right now, but there are several good forks. Try https://github.com/youngcm2/CsvHelper.Excel
I'd be happy for someone to take over this project, should they wish.

**Comment by kfrancis** [comment]
@christophano Happy to do that

**Review by carloshgamboa — APPROVED** [review]

**Review by carloshgamboa — APPROVED** [review]

**Pull request closed without merging**
